### ISSUE TITLE
is this project abandoned? ;-)

### ISSUE THREAD

**Issue by kbrown** [brendonboshell/abandoned#2]
This is what I was looking for.  Not working

kevin@AxioMBP-2BLGTF1-kbrown client % abandoned                      
Looking for package.json in /Users/kevin/axio/client/package.json.
Found 227 packages.
/usr/local/lib/node_modules/abandoned/bin/abandoned.js:79
    modifiedDate = new Date(resp.body.time.modified);
                                           ^

TypeError: Cannot read property 'modified' of undefined
    at Request.afterGet [as _callback] (/usr/local/lib/node_modules/abandoned/bin/abandoned.js:79:44)
    at Request.self.callback (/usr/local/lib/node_modules/abandoned/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/abandoned/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/abandoned/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1252:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by draperunner** [comment]
I have published a fork of this project under the name `ditched`. Have a look! 😊 https://github.com/draperunner/ditched

**Comment by sunshineo** [comment]
@draperunner Can you open the issues section in your project? I want to request for the feature to recursively do the check for all dependencies

**Comment by draperunner** [comment]
@sunshineo done ✅
